language: node_js
node_js:
  - '10.13.0'

cache:
  directories:
    - node_modules

before_install:
  - npm install -g webpack

script:
  - webpack

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
